node('generic'){
    sh 'terraform version'
    checkout([$class: 'GitSCM', 
               branches: [[name: '*/master']], 
               doGenerateSubmoduleConfigurations: false, 
               extensions: [], 
               submoduleCfg: [], 
               userRemoteConfigs: [[
                credentialsId: 'ssh_private_key', 
                url: 'https://github.com/cohencil/jenkins-chaos-master.git']]
    ])

    ansiColor('xterm') {
        dir('terraform') {
            stage('terraform init') {
                sh 'terraform init'
                sh 'terraform workspace select supernova'
            }

            stage('terraform plan') {
                sh 'terraform plan'
            }

            //stage('terraform apply') {
            //    sh 'terraform apply -input=false'
            //}
        }
    }
}