variable "profile" {}
variable "region" {}
variable "az" {}
variable "domain" {}
variable "vpc_id" {}
variable "subnet_id" {}
variable "ami_id" {}
variable "instance_type" {}
variable "volume_size" {}
variable "ssh_keypair_name" {}
variable "instance_name" {}
