jenkins:
  numExecutors: 2
  markupFormatter:
    rawHtml:
      disableSyntaxHighlighting: false

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: ${JENKINS_ADMIN_PASSWORD}

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true

  remotingSecurity:
    enabled: true

credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              scope: GLOBAL
              id: ssh_private_key
              username: admin
              passphrase:
              description:
              privateKeySource:
                directEntry:
                  privateKey: ${GIT_PRIVATE_KEY}

unclassified:
#  globalLibraries:
#    libraries:
#      - name: pipeline-library
#        retriever:
#          modernSCM:
#            scm:
#              git:
#                remote: file:///var/jenkins_lib
#        defaultVersion: master
#        implicit: false
#        allowVersionOverride: true
#        includeInChangesets: true

  simple-theme-plugin:
    elements:
      - cssUrl:
          url: /userContent/material-blue.css

  location:
    adminAddress: webmaster@tikal.io

jobs:
  - script: |-
      def projects = ['terraform']
      projects.each{prj ->
        pipelineJob(prj){
          definition{
            cpsScm{
              lightweight(true)
              scm{
                git{
                  remote {
                    url('https://github.com/cohencil/jenkins-chaos-master.git')
                  }
                  branches("refs/heads/master")
                }
                scriptPath(prj + '/Jenkinsfile')
              }
            }
          }
        }
      }
      # Create views for each fuse group
      # for(i in 1..10) {
      #   listView('g0' + i) {
      #   description('Job view for project g' + i)
      #   jobs {
      #       name('g${i}-.+')
      #     }
      #   }
      # }
tool:
  terraforminstallation:
    installations:
      - name: terraform
        home: ""
        properties:
          - installSource:
              installers:
                - terraformInstaller:
                    id: "0.12.3-linux-amd64"
      - name: "terraform_0.11.14"
        properties:
          - installSource:
              installers:
              - terraformInstaller:
                  id: "0.11.14-linux-amd64"
